version: '3.8'

services:
  postgres:
    build: './database'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feeds
    restart: always

  nats:
    image: nats:latest
    restart: always
  elasticsearch:
    image: elasticsearch:latest
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false