version: '3.8'

services:
  postgres:
    build: './database'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feeds
    restart: always

  nats:
    image: nats:latest
    restart: always
  